### ISSUE TITLE
[Segmentation Fault] [Backtrace] QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()

### ISSUE THREAD

**Issue by Macribit** [Lurkki14/tuxclocker#8]
from konsole
```
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()
KCrash: Application 'tuxclocker' crashing...
KCrash: Attempting to start /usr/lib64/libexec/drkonqi from kdeinit
```

error from drkonqui
```

Application: tuxclocker (tuxclocker), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7ff2c3ae4d80 (LWP 7437))]

Thread 3 (Thread 0x7ff2a7bf0700 (LWP 7439)):
#0  0x00007ff2c1415e98 in read () from /lib64/libpthread.so.0
#1  0x00007ff2bec41a50 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007ff2bebfcc38 in g_main_context_check () from /usr/lib64/libglib-2.0.so.0
#3  0x00007ff2bebfd0d0 in ?? () from /usr/lib64/libglib-2.0.so.0
#4  0x00007ff2bebfd23c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#5  0x00007ff2c1ba270b in QEventDispatcherGlib::processEvents (this=0x14f6be0, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#6  0x00007ff2c1b4399a in QEventLoop::exec (this=this@entry=0x7ff2a7befc80, flags=..., flags@entry=...) at kernel/qeventloop.cpp:225
#7  0x00007ff2c196b03a in QThread::exec (this=<optimized out>) at thread/qthread.cpp:531
#8  0x00007ff2b9e1fd55 in ?? () from /usr/lib64/libQt5DBus.so.5
#9  0x00007ff2c196c7e2 in QThreadPrivate::start (arg=0x7ff2ba097d80) at thread/qthread_unix.cpp:361
#10 0x00007ff2c140c559 in start_thread () from /lib64/libpthread.so.0
#11 0x00007ff2c085681f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7ff2b6e72700 (LWP 7438)):
#0  0x00007ff2c084c07b in poll () from /lib64/libc.so.6
#1  0x00007ff2bc415387 in _xcb_conn_wait () from /usr/lib64/libxcb.so.1
#2  0x00007ff2bc416fba in xcb_wait_for_event () from /usr/lib64/libxcb.so.1
#3  0x00007ff2ba34c668 in QXcbEventQueue::run (this=0x13ad5a0) at qxcbeventqueue.cpp:228
#4  0x00007ff2c196c7e2 in QThreadPrivate::start (arg=0x13ad5a0) at thread/qthread_unix.cpp:361
#5  0x00007ff2c140c559 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ff2c085681f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ff2c3ae4d80 (LWP 7437)):
[KCrash Handler]
#6  0x00007ff2c07f64a6 in __strlen_sse2 () from /lib64/libc.so.6
#7  0x00007ff2c1b877fe in QString::fromUtf8 (size=-1, str=0x71 <error: Cannot access memory at address 0x71>) at ../../include/QtCore/../../src/corelib/tools/qstring.h:572
#8  QVariant::QVariant (this=0x7ffc01866920, val=0x71 <error: Cannot access memory at address 0x71>) at kernel/qvariant.cpp:1881
#9  0x000000000041e9e7 in MainWindow::on_GPUComboBox_currentIndexChanged(int) ()
#10 0x00000000004a9e63 in MainWindow::qt_metacall(QMetaObject::Call, int, void**) ()
#11 0x00007ff2c1b75289 in QMetaObject::activate (sender=sender@entry=0x153ab70, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=5, argv=argv@entry=0x7ffc01866ac0) at kernel/qobject.cpp:3806
#12 0x00007ff2c1b75897 in QMetaObject::activate (sender=sender@entry=0x153ab70, m=m@entry=0x7ff2c3046fe0 <QComboBox::staticMetaObject>, local_signal_index=local_signal_index@entry=5, argv=argv@entry=0x7ffc01866ac0) at kernel/qobject.cpp:3642
#13 0x00007ff2c2a673c1 in QComboBox::currentIndexChanged (this=this@entry=0x153ab70, _t1=<optimized out>) at .moc/moc_qcombobox.cpp:509
#14 0x00007ff2c2a691f3 in QComboBoxPrivate::_q_emitCurrentIndexChanged (this=this@entry=0x153caa0, index=...) at widgets/qcombobox.cpp:1377
#15 0x00007ff2c2a6a6dc in QComboBoxPrivate::setCurrentIndex (this=this@entry=0x153caa0, mi=...) at widgets/qcombobox.cpp:2192
#16 0x00007ff2c2a6a971 in QComboBox::setCurrentIndex (this=<optimized out>, index=index@entry=0) at widgets/qcombobox.cpp:2154
#17 0x00007ff2c2a6ce07 in QComboBoxPrivate::_q_rowsInserted (this=<optimized out>, parent=..., start=<optimized out>, end=<optimized out>) at widgets/qcombobox.cpp:1103
#18 0x00007ff2c2a70729 in QComboBox::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=0x7ffc01866db0) at .moc/moc_qcombobox.cpp:295
#19 0x00007ff2c1b751c5 in QMetaObject::activate (sender=sender@entry=0x170f0d0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=10, argv=argv@entry=0x7ffc01866db0) at kernel/qobject.cpp:3789
#20 0x00007ff2c1b75897 in QMetaObject::activate (sender=sender@entry=0x170f0d0, m=m@entry=0x7ff2c1ff2580 <QAbstractItemModel::staticMetaObject>, local_signal_index=local_signal_index@entry=10, argv=argv@entry=0x7ffc01866db0) at kernel/qobject.cpp:3642
#21 0x00007ff2c1aed00e in QAbstractItemModel::rowsInserted (this=this@entry=0x170f0d0, _t1=..., _t2=<optimized out>, _t3=<optimized out>, _t4=...) at .moc/moc_qabstractitemmodel.cpp:591
#22 0x00007ff2c1af48bb in QAbstractItemModel::endInsertRows (this=this@entry=0x170f0d0) at itemmodels/qabstractitemmodel.cpp:2748
#23 0x00007ff2c24e07de in QStandardItemModelPrivate::rowsInserted (this=<optimized out>, parent=<optimized out>, row=<optimized out>, count=<optimized out>) at itemmodels/qstandarditemmodel.cpp:656
#24 0x00007ff2c24e0eef in QStandardItemPrivate::insertRows (this=0x153cd60, row=row@entry=0, count=count@entry=1, items=...) at itemmodels/qstandarditemmodel.cpp:528
#25 0x00007ff2c24e235b in QStandardItem::insertRow (this=<optimized out>, row=row@entry=0, items=...) at itemmodels/qstandarditemmodel.cpp:1630
#26 0x00007ff2c24e23d3 in QStandardItemModel::insertRow (this=this@entry=0x170f0d0, row=row@entry=0, items=...) at itemmodels/qstandarditemmodel.cpp:2673
#27 0x00007ff2c2a6cf24 in QStandardItemModel::insertRow (aitem=<optimized out>, arow=<optimized out>, this=0x170f0d0) at ../../include/QtGui/../../src/gui/itemmodels/qstandarditemmodel.h:447
#28 QComboBox::insertItem (this=<optimized out>, index=0, icon=..., text=..., userData=...) at widgets/qcombobox.cpp:2306
#29 0x000000000041f8c2 in MainWindow::MainWindow(QWidget*) ()
#30 0x00000000004157a8 in main ()
[Inferior 1 (process 7437) detached]

```

**Comment by Lurkki14** [comment]
What branch is this? The dev and amdpstate branches are experimental, non-feature complete and prone to crashing. Recent development development is done in amdpstatetest, and this might already be fixed in said branch.

**Comment by Macribit** [comment]
> What branch is this? The dev and amdpstate branches are experimental, non-feature complete and prone to crashing. Recent development development is done in amdpstatetest, and this might already be fixed in said branch.

yes is dev branch

**Comment by Macribit** [comment]
ok tried the amdpstatetest branch at least it starts and run, but now everything I do makes the app exit. Should I open a new bug report?

**Comment by Lurkki14** [comment]
It depends on what you mean by anything, since most features aren't implemented in that branch. If you want to test it you should message me directly, since stuff is changing all the time in these experimental branches.

**Comment by Macribit** [comment]
> It depends on what you mean by anything, since most features aren't implemented in that branch. If you want to test it you should message me directly, since stuff is changing all the time in these experimental branches.

yes I try to apply overclock or apply fan speed and it exits.

**Comment by Lurkki14** [comment]
They're not implemented for AMD yet so I'm closing this.
